### ISSUE TITLE
message url

### ISSUE THREAD

**Issue by BarryThePenguin** [unifiedjs/unified-engine-atom#15]
From steelbrain/linter-ui-default#205, there is a url on the `linter` message

eslint uses a url to link to the rule documentation https://github.com/jfmengels/eslint-rule-documentation

`unified-engine-atom` could do something similar

**Comment by wooorm** [comment]
Yes agreed!
I've been wondering if we could somehow align [vfile messages](https://github.com/vfile/vfile#vfilemessagereason-position-ruleid) more with linter messages: maybe supporting suggestions even?!

I'm open to suggestions: do you have ideas?

**Comment by BarryThePenguin** [comment]
When you say supporting `suggestions`, do you mean `solutions`?

```js
solutions?: Array<{
 title?: string,
 position: Range,
 priority?: number,
 currentText?: string,
 replaceWith: string,
} | {
 title?: string,
 position: Range,
 priority?: number,
 apply: (() => any),
}>,
// ^ Possible solutions to the error (user can invoke them at will)
```

**Comment by wooorm** [comment]
Yup, sorry, both like this: https://github.com/wooorm/remark-lint/issues/82, and like this: https://github.com/wooorm/retext-simplify/commit/8ec7ce8c302364795e99327e0951ca94a0d8a68d

**Comment by wooorm** [comment]
First case was meant to be 'solutions', second was meant as suggestions for a better API and more features/properties!

**Comment by BarryThePenguin** [comment]
I like the idea of solutions. A single 'fix'/'apply' function makes sense for `remark-lint`, while the `Array` of solutions makes sense when dealing with `retext` plugins that might provide multiple solutions for fixing an issue.

Something that confused colleagues with `remark` was the stringify settings were seperate from the lint configuration. Neither which impacted one another. Having the 'fix'/'apply' functions might make configuring `remark` simpler.

The other thing I've been thinking about is the difference between `location` and `range`. Atom works with 0-indexed positions ([Range](https://atom.io/docs/api/v1.5.0/Range)). I'm not too sure what the advantages/disadvantages are of 0-indexed positions vs 1-indexed positions. Adding a getter for `range` to a vfile message that returns `toRange(location)` probably makes sense.

And urls. How much ✨ magic ✨  would you want in the url handling? Eslint use [eslint-rule-documentation](https://github.com/jfmengels/eslint-rule-documentation) and determines the url based on the rule name and a map of plugins and repository urls. Could do something similar. It may just be easier for each rule to set it's own value for url in the vfile message, and mention the url property in the vfile documentation.

Also... have you considered using flow?

**Comment by wooorm** [comment]
> I like the idea of solutions. A single 'fix'/'apply' function makes sense for remark-lint, while the Array of solutions makes sense when dealing with retext plugins that might provide multiple solutions for fixing an issue.

* So there’s two ways to fix stuff. One is AST changes (transforms), the other is text fixes. The latter is what ESLint does, it inserts, removes, or replaces a few characters in the original file. The first sounds really cool, but there are many rules that cannot be fixed in through AST changes (as it’s an AST, not a CST). Transforms cannot work together with text replacements, as transforms make the tree “unstable” (not representing the origin document) which means text fixes cannot be applied.
* Finally, the unified API (so not the CLI) cannot apply fixes: the original document is forgotten, but even if it could, it shouldn’t, as now there’s a transformed document (destination file) and a fixed document (based on the original).
* If we do fixes, it should probably be related to vfile, as vfile handles files and their messages.

> Something that confused colleagues with remark was the stringify settings were seperate from the lint configuration. Neither which impacted one another. Having the 'fix'/'apply' functions might make configuring remark simpler.

Yes, I get that! Though `fix` and `apply` cannot be used together with tree transforms, as mentioned before

> The other thing I've been thinking about is the difference between location and range. Atom works with 0-indexed positions (Range). I'm not too sure what the advantages/disadvantages are of 0-indexed positions vs 1-indexed positions. Adding a getter for range to a vfile message that returns toRange(location) probably makes sense.

Could you expand on how you see that working?

> And urls. How much ✨ magic ✨ would you want in the url handling? Eslint use eslint-rule-documentation and determines the url based on the rule name and a map of plugins and repository urls. Could do something similar. It may just be easier for each rule to set it's own value for url in the vfile message, and mention the url property in the vfile documentation.

I’d say no magic at all, just a `url` property :)

> Also... have you considered using flow?

No, reason: I don’t like compiling, I like JavaScript!

**Comment by wooorm** [comment]
I opened https://github.com/vfile/vfile/issues/21 to work on this!
